log:
  level: debug
  disable_sentry: true

db:
  url: "postgres://github:github@localhost:5436/github?sslmode=disable"

cache:
  default_expiration: 35m #time for default duration of each cache item (f.e. 10m5s)
  cleanup_interval: 5m #interval with which garbage collector will work (f.e. 10m5s)

amqp:
  topic: "github"
  publisher: "amqp://guest:guest@localhost:5672/" #github_publisher
  subscriber: "amqp://guest:guest@localhost:5672/" #github_receiver

github: #access token for superuser
  token: "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"

listener:
  addr: :7000

registrator:
  outer_url: "http://localhost:8000/integrations/orchestrator/modules" #configure MODULE outer endpoint
  inner_url: "http://localhost:7000/integrations/github" #configure MODULE inner endpoint
  endpoint: "github" #configure MODULE endpoint
  topic: "github" #configure MODULE topic

jwt:
  secret: SuPeR SeCrEt PhRaSe
  refresh_life: 6h
  access_life: 10m5s

cop:
  disabled: true
  endpoint: "http://..."
  upstream: "http://..."
  service_name: core
  service_port: 80
