log:
  level: debug
  disable_sentry: true

db:
  url: "postgres://github:github@localhost:5447/github?sslmode=disable"

cache:
  default_expiration: 35m #time for default duration of each cache item (f.e. 10m5s)
  cleanup_interval: 5m #interval with which garbage collector will work (f.e. 10m5s)

amqp:
  topic: "github"
  publisher: "amqp://guest:guest@localhost:5672/" #github_publisher
  subscriber: "amqp://guest:guest@localhost:5672/" #github_receiver

github: #access token for superuser
  token: "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"

listener:
  addr: :7005

registrator:
  outer_url: "http://localhost:8000/integrations/orchestrator/modules" #endpoint to register MODULE
  inner_url: "http://localhost:7005/integrations/github" #endpoint to MODULE itself
  topic: "github" #MODULE topic
  title: "Github" #MODULE title
  prefix: "https://github.com"

jwt:
  secret: SuPeR SeCrEt PhRaSe
  refresh_life: 6h
  access_life: 10m5s

cop:
  disabled: true
  endpoint: "http://..."
  upstream: "http://..."
  service_name: core
  service_port: 80
