log:
  level: debug
  disable_sentry: true

db:
  url: "postgres://github:github@localhost:5447/github?sslmode=disable"

amqp:
  topic: "github"
  publisher: "amqp://guest:guest@localhost:5672/" #github_publisher
  subscriber: "amqp://guest:guest@localhost:5672/" #github_receiver

github: #access token for superuser
  token: "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"

listener:
  addr: :7005

registrator:
  outer_url: "http://localhost:8000/integrations/orchestrator/modules" #endpoint to register MODULE
  inner_url: "http://localhost:7005/integrations/github" #endpoint to MODULE itself
  topic: "github" #MODULE topic
  title: "Github" #MODULE title
  prefix: "https://github.com"
  is_module: true

jwt:
  secret: SuPeR SeCrEt PhRaSe
  refresh_life: 6h
  access_life: 10m5s

cop:
  disabled: true
  endpoint: "http://..."
  upstream: "http://..."
  service_name: core
  service_port: 80
